namespace ScholarFlow.Modules.Examination.DTOs;

public sealed record SessionDetailDto(
    Guid SessionId,
    Guid? PaperId,
    Guid? SubjectId,
    Guid? TopicId,
    string? PaperTitle,
    DateTime StartTime,
    DateTime ServerNow,
    DateTime? ExpiresAt,
    int? TimeLimitMinutes,
    DateTime? EndTime,
    string Status,
    string Mode,
    decimal ObtainedMarks,
    decimal TotalMarks,
    decimal Percentage,
    bool IsPassing,
    int CorrectCount,
    int WrongCount,
    int SkippedCount,
    int TimeTakenSeconds,
    bool AffectsMastery,
    bool HasReviewData,
    DateTime? ReviewAvailableUntil,
    List<SessionResponseDto> Responses);
